export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const SALESDASH_ERROR = "SALESDASH_ERROR";
export const SALESDASH_LOADING = "SALESDASH_LOADING";
export const SALESDASH_SUCCESS = "SALESDASH_SUCCESS";
export const STOCKSDASH_LOADING = "STOCKSDASH_LOADING";
export const STOCKSDASH_SUCCESS = "STOCKSDASH_SUCCESS";
export const STOCKSDASH_ERROR = "STOCKSDASH_ERROR";

export const STOCKS_LOADING = "STOCKS_LOADING";
export const STOCKS_SUCCESS = "STOCKS_SUCCESS";
export const STOCKS_ERROR = "STOCKS_ERROR";
export const STOCK_DELETE_SUCCESS = "STOCK_DELETE_SUCCESS";
export const STOCK_DELETE_ERROR = "STOCK_DELETE_ERROR";

export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_ERROR = "ORDERS_ERROR";
export const ORDERS_DELETE_SUCCESS = "ORDERS_DELETE_SUCCESS";
export const ORDERS_DELETE_ERROR = "ORDERS_DELETE_ERROR";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const ORDERS_MODAL_OPEN = "ORDERS_MODAL_OPEN";
export const ORDERS_MODAL_CLOSE = "ORDERS_MODAL_CLOSE";

export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_ERROR = "ADD_STOCK_ERROR";
export const MODIFY_STOCK_DATA = "MODIFY_STOCK_DATA";
export const SET_STOCK_DATA = "SET_STOCK_DATA";

export const ADD_ORDERS_SUCCESS = "ADD_ORDERS_SUCCESS";
export const ADD_ORDERS_ERROR = "ADD_ORDERS_ERROR";
export const MODIFY_ORDERS_DATA = "MODIFY_ORDERS_DATA";
export const SET_ORDERS_DATA = "SET_ORDERS_DATA";

// export const STOCK_MODAL_ACTIONS = {
//     ADD_STOCK: 'ADD_STOCK',
//     UPDATE_STOCK: 'UPDATE_STOCK'
// }

export const EDIT_STOCK_SUCCESS = "EDIT_STOCK_SUCCESS";
export const EDIT_STOCK_ERROR = "EDIT_STOCK_ERROR";

export const EDIT_ORDERS_SUCCESS = "EDIT_ORDERS_SUCCESS";
export const EDIT_ORDERS_ERROR = "EDIT_ORDERS_ERROR";

export const TABLE_SELECT = "TABLE_SELECT";
export const STOCKS_PAGE_CHANGE = "STOCKS_PAGE_CHANGE";
export const ORDERS_PAGE_CHANGE = "ORDERS_PAGE_CHANGE";
